---
- name: Set facts
  tags: ['docker-compose-systemd']
  ansible.builtin.set_fact:
    docker_service_config_dir: "{{ docker_service_config_dest }}/{{ docker_service_name }}"

- name: Ensure service group
  become: true
  tags: ['docker-compose-systemd']
  ansible.builtin.group:
    name: "{{ docker_service_group }}"
    gid: "{{ docker_service_guid | default(omit, true) }}"

- name: Ensure service user
  become: true
  tags: ['docker-compose-systemd']
  ansible.builtin.user:
    name: "{{ docker_service_user }}"
    group: "{{ docker_service_group }}"
    uid: "{{ docker_service_guid | default(omit, true) }}"
    append: true
    groups: "{{ docker_service_user_additional_groups }}"

- name: Ensure docker group membership
  when: docker_service_user_add_to_docker_group | bool
  become: true
  tags: ['docker-compose-systemd']
  ansible.builtin.user:
    name: "{{ docker_service_user }}"
    append: true
    groups:
      - docker

- name: Ensure external user group membership
  loop: "{{ docker_service_group_additional_members }}"
  become: true
  check_mode: false
  tags: ['docker-compose-systemd']
  ansible.builtin.user:
    name: "{{ item }}"
    append: true
    groups:
      - "{{ docker_service_group }}"

- name: Ensure service config directory
  become: true
  tags: ['docker-compose-systemd']
  ansible.builtin.file:
    path: "{{ docker_service_config_dir }}"
    state: directory
    owner: "{{ docker_service_user }}"
    group: "{{ docker_service_group }}"
    mode: "{{ docker_service_config_dir_mode }}"

- name: Ensure additional service directories
  become: true
  loop: "{{ docker_service_additional_directories }}"
  loop_control:
    label: "{{ item.path }}"
  tags: ['docker-compose-systemd']
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default(docker_service_user) }}"
    group: "{{ item.group | default(docker_service_group) }}"
    mode: "{{ item.mode | default(docker_service_config_dir_mode) }}"
    state: directory

- name: Ensure systemd service file
  become: true
  notify: Enable and restart docker service
  tags: ['docker-compose-systemd']
  ansible.builtin.template:
    src: templates/systemd.service.j2
    dest: /etc/systemd/system/{{ docker_service_name }}.service
    owner: root
    group: root
    mode: "755"

- name: Ensure docker-compose file
  become: true
  notify: Enable and restart docker service
  tags: ['docker-compose-systemd']
  ansible.builtin.copy:
    dest: "{{ docker_service_config_dir }}/docker-compose.yml"
    content: "{{ docker_service_configuration | to_nice_yaml(indent=2, sort_keys=false) }}"
    owner: "{{ docker_service_user }}"
    group: "{{ docker_service_group }}"
    mode: "{{ docker_service_config_file_mode }}"

- name: Ensure service template file(s)
  become: true
  loop: "{{ docker_service_templates }}"
  loop_control:
    label: "{{ item.dest }}"
  notify: |
    {%- if docker_service_templates_notify_handlers | bool -%}
    Enable and restart docker service
    {%- else -%}
    {{ omit }}
    {%- endif -%}
  tags: ['docker-compose-systemd']
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default(docker_service_user) }}"
    group: "{{ item.group | default(docker_service_group) }}"
    mode: "{{ item.mode | default(docker_service_config_file_mode) }}"

- debug:
    var: docker_service_config_file_mode

- debug:
    var: docker_service_periodic_restart_enabled

- debug:
    var: docker_service_periodic_restart_cron

- name: Ensure periodic restart cron job
  become: true
  when: docker_service_periodic_restart_enabled | bool
  tags: ['docker-compose-systemd']
  ansible.builtin.cron:
    name: "{{ docker_service_name }}-restart"
    job: systemctl stop "{{ docker_service_name }}" && sleep 30 && systemctl start "{{ docker_service_name }}"
    weekday: "{{ (docker_service_periodic_restart_cron.split(' '))[4] }}"
    month:   "{{ (docker_service_periodic_restart_cron.split(' '))[3] }}"
    day:     "{{ (docker_service_periodic_restart_cron.split(' '))[2] }}"
    hour:    "{{ (docker_service_periodic_restart_cron.split(' '))[1] }}"
    minute:  "{{ (docker_service_periodic_restart_cron.split(' '))[0] }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
